"""Initial migration

Revision ID: 65b955ecb920
Revises: 
Create Date: 2025-12-22 16:30:28.145109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b955ecb920'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('vc_firm', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_logo_url', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('job_category', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('date_scraped', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('application_url', sa.String(), nullable=False),
    sa.Column('application_platform', sa.String(), nullable=False),
    sa.Column('custom_questions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('idx_active_category_sector', 'jobs', ['is_active', 'job_category', 'sector'], unique=False)
    op.create_index('idx_company_active', 'jobs', ['company_name', 'is_active'], unique=False)
    op.create_index(op.f('ix_jobs_company_name'), 'jobs', ['company_name'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_job_category'), 'jobs', ['job_category'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_sector'), 'jobs', ['sector'], unique=False)
    op.create_index(op.f('ix_jobs_source_url'), 'jobs', ['source_url'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('sectors', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('job_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('demographics', sa.JSON(), nullable=True),
    sa.Column('rejected_job_urls', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('daily_application_limit', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OUTSTANDING', 'APPLIED', 'INTERVIEWING', 'OFFERED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('date_swiped', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_responses', sa.JSON(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('interview_stage', sa.String(), nullable=True),
    sa.Column('offer_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_index('idx_user_date', 'applications', ['user_id', 'date_swiped'], unique=False)
    op.create_index('idx_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('swipe_history',
    sa.Column('swipe_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('undone', sa.Boolean(), nullable=False),
    sa.Column('undo_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('swipe_id')
    )
    op.create_index('idx_user_timestamp', 'swipe_history', ['user_id', 'timestamp'], unique=False)
    op.create_table('user_job_queue',
    sa.Column('queue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('shown', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index('idx_user_score', 'user_job_queue', ['user_id', 'relevance_score'], unique=False)
    op.create_index('idx_user_shown', 'user_job_queue', ['user_id', 'shown'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_shown', table_name='user_job_queue')
    op.drop_index('idx_user_score', table_name='user_job_queue')
    op.drop_table('user_job_queue')
    op.drop_index('idx_user_timestamp', table_name='swipe_history')
    op.drop_table('swipe_history')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index('idx_user_status', table_name='applications')
    op.drop_index('idx_user_date', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_source_url'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_sector'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_category'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_name'), table_name='jobs')
    op.drop_index('idx_company_active', table_name='jobs')
    op.drop_index('idx_active_category_sector', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
